# Generated by Django 4.2.16 on 2024-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquanet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductivityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('threshold_min', models.FloatField(default=50.0)),
                ('threshold_max', models.FloatField(default=1500.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PHReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('threshold_min', models.FloatField(default=6.5)),
                ('threshold_max', models.FloatField(default=8.5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='realtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('conductivity', models.FloatField(default=0)),
                ('turbidity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('threshold_min', models.FloatField(default=0.0)),
                ('threshold_max', models.FloatField(default=30.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurbidityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('threshold_min', models.FloatField(default=0.0)),
                ('threshold_max', models.FloatField(default=5.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
